ministryofjustice/opg-sirius-end-to-end-tests

.github/dependabot.yml, Dockerfile
- Add Dependabot updates for the Dockerfile
- Pin cypress-grep to 2.12.0
- Pin cypress-failed-log to 2.9.2
=> Add Dependbot updates for the Dockerfile

cypress/integration/lpa/cases/change-status.spec.js, cypress/integration/lpa/cases/create-warning.spec.js, cypress/integration/lpa/cases/epa.spec.js, cypress/integration/lpa/cases/lpa.spec.js, cypress/integration/lpa/cases/timeline.spec.js, cypress/integration/lpa/donors/link.spec.js, cypress/support/lpa-commands.js, package-lock.json, package.json
Adds tests for EPAs, the timeline and donor links (which admittedly aren't "case" tests but were on the ticket).
I also changed the `createDonor` and `createLpa` support functions to return the whole object, so that tests can pull other fields (e.g. UID)
Fixes VEGA-1217 #minor
=> Migrate case tests from Screenplay

.github/workflows/build.yml, .gitignore, Makefile
- SW-5434 - Pull Sirius build artifacts container and use to run tests against Sirius #minor
- SW-5434 - Move test-results dir #patch
=> SW-5434 - Run E2E Tests against local Sirius #minor"

Dockerfile
This ensures we use the lockfile, and matches the behaviour if Cypress is run locally.
#minor
=> Use NPM install rather than manual installations

cypress/integration/lpa/cases/documents.spec.js
Seems to still be failing, now with "`cy.click()` failed because this element is detached from the DOM". Hopefully by querying for the button again the problem will be solved...
=> VEGA-1218 Requery for RetrieveDraft button

cypress/integration/supervision/clients/edit-client.spec.js, cypress/integration/supervision/dashboard/client-dashboard.spec.js, cypress/integration/supervision/letters/create-letter.spec.js
Aliases the form container, allowing Cypress to handle retries until the form is reattached
=> sw-5440: Edit client test fix

cypress/integration/supervision/clients/edit-client.spec.js
Re-triages edit client test as it fails in Jenkins (but not GitHub Actions)
=> sw-5435: Triage Edit Client

cypress/integration/lpa/cases/change-status.spec.js
They'll be replaced with a iframe-based test once the widget is enabled.
For VEGA-1238 #patch
=> Temporarily remove the change status tests

cypress/e2e/lpa/cases/administration.cy.js, cypress/e2e/lpa/cases/allocate-case.cy.js, cypress/e2e/lpa/cases/create-event.cy.js, cypress/e2e/lpa/cases/create-relationship.cy.js, cypress/e2e/lpa/cases/documents.cy.js, cypress/e2e/lpa/cases/tasks.cy.js, cypress/e2e/lpa/donors/donor.cy.js
XHR-request-waiting isn't a particularly good technique in general, and we've specifically found that it sometimes is started after the XHR is already complete, causing the test to hang until failing.
Hence, replace some straightforward XHR-request-waiting with DOM-waiting to hopefully make some of our tests more reliable.
VEGA-1395 #patch
=> Wait on DOM elements, not XHR requests

.github/workflows/build.yml
Dependabot doesn't have the required secrets to pull the latest green build from ECR
#patch
=> Don't run local tests as Dependabot

cypress/e2e/lpa/donors/link.cy.js
`.type('{enter}')` and `("button").click()` are both submitting the form, we don't need both of them
#patch
=> Don't double-enter the person search form

cypress/e2e/lpa/cases/complaints.cy.js
As received date is now a mandatory field when creating a complaint
=> VEGA-1669 set receiveddate field in add complaints test

cypress/e2e/lpa/cases/epa.cy.js, cypress/e2e/lpa/cases/lpa.cy.js
`.action-widget-content` has started matching hidden elements, and `.within()` only works if a single element has been found. Specify that we're only interested in the visible one.
#patch
=> Fix widget CSS selector

cypress/e2e/lpa/cases/create-event.cy.js, cypress/e2e/lpa/cases/investigations.cy.js, cypress/e2e/lpa/cases/tasks.cy.js
- Wait for the *case* to load, not just the donor, since the widgets rely on having a "selected case"
- When interacting with the task list, scroll it into view first to ensure that the buttons aren't covered by other fixed elements (e.g. the page header)
Fixes VEGA-1718 #patch
=> Attempt to fix a few common E2E issues

cypress/e2e/lpa/cases/administration.cy.js, cypress/e2e/lpa/cases/allocate-case.cy.js, cypress/e2e/lpa/cases/change-status.cy.js, cypress/e2e/lpa/cases/complaints.cy.js, cypress/e2e/lpa/cases/create-event.cy.js, cypress/e2e/lpa/cases/create-relationship.cy.js, cypress/e2e/lpa/cases/documents.cy.js, cypress/e2e/lpa/cases/epa.cy.js, cypress/e2e/lpa/cases/investigations.cy.js, cypress/e2e/lpa/cases/lpa.cy.js, cypress/e2e/lpa/cases/search.cy.js, cypress/e2e/lpa/cases/tasks.cy.js, cypress/e2e/lpa/cases/timeline.cy.js, cypress/e2e/lpa/cases/warnings.cy.js, cypress/e2e/lpa/donors/donor.cy.js, cypress/e2e/lpa/donors/link.cy.js, cypress/support/lpa-commands.js
Attempts to address two problems:
1. Wait for the app to render fully before interacting with it
For example, when "Add Investigation" is clicked before the page has rendered fully, the app will error with the below and stop the iframe from loading. This affects most initial click events
```
TypeError: Cannot read properties of undefined (reading 'id')
at new InvestigationCtrl (investigation.ctrl.js:171:72)
at Object.instantiate (angular.js:5223:14)
at $controller (angular.js:11829:28)
at widgetCtrl.directive.js:14:21
at Scope.$digest (angular.js:19269:34)
at ChildScope.$apply (angular.js:19630:24)
at HTMLAnchorElement.<anonymous> (angular.js:29127:19)
at HTMLAnchorElement.dispatch (jquery.js:5494:27)
at elemData.handle (jquery.js:5298:28)
```
2. `.contains` seems to be a bit slower than …
=> SW-6445 Attempt to fix some flakiness

cypress/support/commands.js
When we force SSO login in non-dev environments, `/auth/logout` will redirect to a 401 page. This change ensures that the tests will still pass.
For VEGA-1719 #patch
=> Allow `/auth/logout` to give 401

cypress/e2e/lpa/cases/warnings.cy.js
temporarily commented out remove warning test as does not work with new modal popup. Will add back in once frontend changes merged. 
VEGA-1799 #patch
=> VEGA-1799 disable remove warning test to merge new modal popup

cypress/e2e/lpa/cases/warnings.cy.js
Added an extra test for creating & removing warnings on the donor record as well as on a case so that we cover scenarios for both pre-existing warnings and new warnings that will on case(s) going forward
=> VEGA-1799 re-enable remove warning test

cypress/fixtures/deputy-contact/minimal.json
Updated the create deputy contact test to send booleans in the form of strings (as Go sends them), instead of actual booleans. This doesn't affect the current test performance, but allows the manage deputy contact branch in sirius to pass e2e tests.
=> SW-5017 Updated create test to send string bools

cypress/e2e/supervision/clients/visits/extend-visit.cy.js
Updated extend visit test to use tomorrow's date as the report due date. This currently doesn't affect any tests, but is needed for ticket SW-6749 to pass tests, as it requires this date to always be in the future when first set.
=> SW-6749 Updated extend visit test to use tomorrow's date

cypress/e2e/supervision/clients/visits/extend-visit.cy.js
Specified to use the English date format when getting tomorrow's date, as currently this uses the American format. This doens't affect any current tests, but is required for the sirius PR for this ticket
=> SW-6749 Specified locale to fix date behaviour in pipeline

cypress/e2e/supervision/clients/visits/extend-visit.cy.js
Updated the extend visit test to use next week's date as the new report due date. This doesn't affect the current test performance, but is necessary to merge in ticket SW-6749, which adds validation to this field that ensures the date is always in the future.
=> SW-6749 Updated extend report due date to use next week's date

cypress.config.js, cypress/e2e/supervision/clients/edit-client.cy.js, cypress/support/forms.js
- Increase default timeout for requests in a wait() to go out from 5s to 60s
- Increase default timeout for responses in a wait() (and some other calls) to go out from 30s to 60s
- Increase timeout for Tiny MCE to initialise from 2s to 60s
- Remove 2s timeout on waiting for firstname field in Edit Client test
=> Increase timeouts

cypress/e2e/supervision/deputies/add-deputy.cy.js
Test failed intermittently as the button was visible but not yet enabled
=> Wait for #add-deputy-button to be enabled

cypress/e2e/supervision/clients/edit-client.cy.js
Not updated weights as Andy said it only needs doing when a new test is added, this is a small change so not required.
=> sw-7328 remove caserec check from edit client test #minor;

cypress/e2e/supervision/deputies/add-deputy.cy.js
=> sw-7292 stripping out newsletter test fix

cypress/e2e/lpa/cases/documents.cy.js
This ensures it will be available in the document list, rather than risking a race condition.
For VEGA-2769 #patch
=> Wait for document to appear on timeline before opening it
