cypress/integration/supervision/clients/add-new-client.spec.js
cypress/integration/supervision/dashboard/client-dashboard.spec.js
cypress/integration/supervision/dashboard/dashboard.spec.js
cypress/integration/supervision/dashboard/reassign-client.spec.js

- Test dashboard navigation for Create Client
- Test Searching for a non-existent client
- Test Createing a new Client via the UI

Add more client tests

---

.gitignore
Dockerfile
cypress.json
cypress/.gitignore
cypress/plugins/index.js
cypress/support/index.js

- Add cypress-failed-log to make seeing failures easier
- Update Cypress container

Add cypress-failed-log

---

Dockerfile

Slight change to the docker build to not rely on upstream updates.

Make sure we have updated OS level packages pulled in

---

cypress/integration/supervision/clients/edit-client.spec.js
cypress/integration/supervision/dashboard/client-dashboard.spec.js
cypress/integration/supervision/dashboard/reassign-client.spec.js
cypress/integration/supervision/letters/create-letter.spec.js
cypress/support/client-commands.js
cypress/support/commands.js
cypress/support/index.js

- Add test for Edit Client
- Move create minimal Client to a common step

Add Edit Client test

---

Dockerfile
docker-compose.yml

Update the image to remove most of the issues. 
- Move to bullseye-slim
- Remove some build steps and dependencies
- run as node user
It's still a fairly hefty image despite this.

Container experiment

---

Dockerfile

Reverts ministryofjustice/opg-sirius-end-to-end-tests#25

Revert "#patch: Bump node from 16-bullseye-slim to 17-bullseye-slim"

---

cypress/integration/lpa/cases/documents.spec.js

VEGA-1218 Wait for the draft to be created before checking iframe

---

cypress/integration/lpa/cases/documents.spec.js

It's still flakey on Sirius's master pipeline

Remove publish/compare test for now

---

cypress/integration/lpa/cases/create-event.spec.js

Will fail until https://github.com/ministryofjustice/opg-sirius/pull/6492 is merged

VEGA-1245 Add test to create an event

---

cypress/integration/lpa/donors/donor.spec.js

Added tests for creating and editing a donor
#minor

VEGA-1216 Migrate donor tests

---

cypress/integration/supervision/clients/add-event.spec.js

Test to cover functionality for SW-5477 in https://github.com/ministryofjustice/opg-sirius/pull/6085/files

Test for pasted data cleanup

---

cypress/fixtures/lpa/minimal.json
cypress/integration/lpa/cases/administration.spec.js
cypress/integration/lpa/cases/search.spec.js

Migrated e2e tests for search.feature and administration.feature
VEGA-1219 #patch

VEGA-1219 Migrate search and admin e2e tests

---

cypress/integration/lpa/cases/administration.spec.js

To allow https://github.com/ministryofjustice/opg-sirius/pull/7042 to build, without breaking all other builds

VEGA-1253 Comment out the edit dates test

---

cypress/integration/lpa/cases/create-relationship.spec.js

Will be looked at properly in https://opgtransform.atlassian.net/browse/VEGA-1351, but for now is blocking master builds

Temporarily remove create relationship test

---

cypress/integration/lpa/donors/link.spec.js

Add person link test

---

cypress/integration/supervision/clients/edit-client.spec.js

Reverts ministryofjustice/opg-sirius-end-to-end-tests#75

Revert "sw-5435: Edit client v2"

---

.github/workflows/build.yml

Trigger remote testing on Jenkins

---

cypress/fixtures/user/system-admin.json
cypress/integration/lpa/cases/administration.spec.js
cypress/support/commands.js

The LPA Manager doesn't have sufficient permission to edit dates.
VEGA-1332 #patch

Login as System Admin for admin tests

---

cypress/integration/lpa/cases/change-status.spec.js

Now using iframes
VEGA-1238 #patch

Re-add change status test

---

.github/dependabot.yml
cypress/integration/lpa/donors/donor.spec.js

Whilst we switch to the iframe'd version
Also enable dependabot for NPM dependencies
For VEGA-1240 #patch

Temporarily remove Create Donor test

---

.github/dependabot.yml
.github/workflows/build.yml

And use `-` as the separator in the branch name
#patch

Prevent dependabot from build steps it can't do

---

cypress/integration/lpa/donors/donor.spec.js

Using embedded iframe rather than AngularJS form
Fixes VEGA-1240 #minor

Add new Create donor test

---

cypress/e2e/lpa/donors/donor.cy.js

As we switch to the iframe version
VEGA-1244 #patch

Disable Edit Donor test temporarily

---

.github/workflows/build.yml

It doesn't have permission to create a GitHub tag
#patch

Stop dependabot trying to bump version

---

cypress/e2e/lpa/donors/donor.cy.js

To use the new iframe-based form
VEGA-1244 #minor

Add new Edit Donor test

---

cypress/e2e/lpa/cases/tasks.cy.js

for https://github.com/ministryofjustice/opg-sirius/pull/8050

VEGA-1570 Make task wait work for new route

---

.github/workflows/build.yml

To see if GitHub Actions is happy to trigger this
#patch

Try encoding Jenkins URI path

---

README.md
cypress.config.js
cypress/support/e2e.js
package-lock.json
package.json

Update to official new plugin and change usage documentation to be more accurate.

Move to official cypress grep plugin

---

cypress/e2e/lpa/cases/documents.cy.js

Adds create draft document test to use the new embedded document form
#minor

VEGA-1239 e2e test for embedded create document widget

---

Makefile
cypress.config.js
cypress/e2e/supervision/clients/documents/open-document.cy.js
cypress/parallel-weights.json
cypress/support/document-commands.js
cypress/support/e2e.js
package-lock.json
package.json

This PR is to rewrite the open document smoke journey test in Cypress and add it to a documents test suite inside the client testing folder.

SW-6207 add new document test suite for clients

---

cypress/e2e/common/login.cy.js
cypress/fixtures/user/allocations.json
cypress/fixtures/user/case-manager.json
cypress/fixtures/user/finance-manager.json
cypress/fixtures/user/finance-reporting.json
cypress/fixtures/user/lay.json
cypress/fixtures/user/lpa-manager.json
cypress/fixtures/user/public-api.json
cypress/fixtures/user/system-admin.json
cypress/support/commands.js

Stop using Membrane login so that we can remove it from Sirius
#minor

Use Mock OAuth login

---

cypress/e2e/supervision/clients/record-client-death-confirmation.cy.js

This PR is to port over the `record-client-death-confirmation` test from Sirius to Cypress in this repo.

SW-5436 Create Client Record Death Confirmation Cypress Tests

---

cypress/e2e/supervision/clients/visits/add-visit.cy.js
cypress/e2e/supervision/clients/visits/edit-visit.cy.js
cypress/parallel-weights.json

This PR is to add the `add-visit` smoke journey test to the e2e repo.

SW-6189 Move Add Visit smoke journey test to Cypress

---

cypress.config.js
cypress/e2e/supervision/clients/edit-client.cy.js

https://github.com/cypress-io/cypress/issues/5830

SW-6482 Fix flaky edit-client test

---

cypress/e2e/lpa/cases/warnings.cy.js

VEGA-1937 re-enable e2e warnings tests

---

cypress/e2e/supervision-deputy-hub/deputy-contacts.cy.js
cypress/fixtures/deputy-contact/minimal.json
cypress/support/deputy-commands.js

Created test that ensures a deputy contact timeline event is created when creating a deputy contact

SW-4995 Created test for deputy contact timeline event

---

cypress/e2e/supervision-deputy-hub/deputy-contacts.cy.js
cypress/fixtures/deputy-contact/minimal.json

Created test to ensure a timeline event is created on edit of a deputy contact

SW-5017 Created edit deputy contact timeline test

---

cypress/e2e/supervision/dashboard/dashboard.cy.js

sw-6621 fxing test to new dashboard #patch

---

cypress/e2e/supervision/finance/client-finance-tab.cy.js

I didn't update the weights file as I only amended some dates.

sw-7123 fix years in test

---

cypress/e2e/supervision/deputies/edit-deputy.cy.js
cypress/e2e/supervision/report/lodge-report.cy.js
cypress/e2e/supervision/report/reset-report.cy.js
cypress/e2e/supervision/report/review-report.cy.js

Not updated weights but I will in the second PR that uncomments this test

Sw 7054 fix e2e tests for adding dob label hints

---

cypress/e2e/supervision/orders/edit-status.cy.js

Updated the order details status label assertions, commented out until Sirius PR is merged

SW-7050 Updated order details status label assertions

---

.github/renovate.json

VEGA-2482 change patch minor renovate schedule to monthly #patch

---

cypress/e2e/supervision/finance/client-finance-tab.cy.js
cypress/e2e/supervision/orders/edit-status.cy.js

sw-7055 improve attribute grabbing for move to accessible radio buttons

---

cypress/e2e/supervision-deputy-hub/navigation.cy.js
cypress/e2e/supervision-firm-deputy-hub/navigation.cy.js
cypress/e2e/workflow/navigation.cy.js

sw-7115 update tests as sirius link now shows in microservices

---

.github/renovate.json

VEGA-2577 increase renovate threshold

---

cypress/e2e/supervision/clients/events/events.cy.js
cypress/e2e/supervision/clients/record-client-death-confirmation.cy.js
cypress/e2e/supervision/documents/deleting-document.cy.js

sw-5882 deletion test for docs

---

cypress/e2e/supervision/clients/events/events.cy.js
cypress/e2e/supervision/clients/record-client-death-confirmation.cy.js
cypress/e2e/supervision/clients/record-client-death-notification.cy.js
cypress/e2e/supervision/deputies/add-deputy.cy.js
cypress/e2e/supervision/documents/deleting-document.cy.js
cypress/e2e/supervision/orders/edit-status.cy.js

Sw 5882 client doc deletion

---

cypress/e2e/supervision/clients/add-event.cy.js
cypress/e2e/supervision/clients/add-task.cy.js
cypress/e2e/supervision/clients/add-warning.cy.js
cypress/e2e/supervision/clients/record-client-death-confirmation.cy.js
cypress/e2e/supervision/clients/record-client-death-notification.cy.js
cypress/e2e/supervision/clients/risk-score.cy.js
cypress/e2e/supervision/clients/visits/extend-visit.cy.js
cypress/e2e/supervision/contacts/remove-contact.cy.js
cypress/e2e/supervision/documents/replace-document.cy.js
cypress/e2e/supervision/orders/create-order.cy.js
cypress/e2e/supervision/orders/edit-order.cy.js
cypress/e2e/supervision/orders/edit-supervision-level.cy.js
cypress/e2e/supervision/report/abandon-report.cy.js
cypress/e2e/supervision/report/edit-report-due-date.cy.js
cypress/e2e/supervision/report/lodge-report.cy.js
cypress/e2e/supervision/report/override-report-type.cy.js
cypress/e2e/supervision/report/preselect-for-review.cy.js
cypress/e2e/supervision/report/review-report.cy.js
cypress/support/forms.js

sw-7508: Makes the text editor conditional to allow for TinyMCE removal

---

cypress/e2e/supervision/orders/bonds/edit-bond.cy.js

The default error message is changing, so turn off this test step until the new one is in place.
#patch

Temporarily turn off test step

---

cypress/e2e/supervision/report/override-report-type.cy.js

pfs-319: Removes unnecessary fetch of finance calls
